export interface EditorialSection {
  title: string;
  introduction: string;
  details: string;
  checklist?: string[];
}

export interface ArticleEditorial {
  subtitle: string;
  takeaways: string[];
  sections: EditorialSection[];
  practicalSteps: string[];
  conclusion: string;
}

const editorials: Record<string, ArticleEditorial> = {
  "1": {
    subtitle: "A practical guide to state, effects, reusable logic and the decisions that keep modern React components predictable.",
    takeaways: ["Treat state as the minimum data required to describe the UI", "Use effects only to synchronize with systems outside React", "Extract custom hooks around reusable behaviour, not arbitrary code", "Prefer derived values and event handlers over extra state and effects"],
    sections: [
      { title: "Start with the component’s data model", introduction: "Before adding a hook, identify what can change, what can be calculated, and what belongs outside the component. This prevents state from becoming a second copy of props or derived information.", details: "A focused state model is easier to update because each value has one clear owner. If a filtered list can be calculated from items and a search term, calculate it during render instead of storing a third state value that can become stale.", checklist: ["Store user-driven values and asynchronous status", "Calculate totals, filters and labels during render", "Keep related transitions close to the event that caused them"] },
      { title: "Use state updates that survive real interaction", introduction: "useState is simple, but update strategy matters when several events can run before React commits a render. When the next value depends on the previous value, use the functional update form.", details: "State should be treated as an immutable snapshot. Replace objects and arrays instead of mutating them, and split unrelated state when those values change independently. For complex transitions with explicit events, a reducer can make the rules easier to inspect and test.", checklist: ["Use functional updates for counters and queued changes", "Never mutate an existing object or array", "Consider useReducer when many events update related state"] },
      { title: "Effects are synchronization boundaries", introduction: "An effect is appropriate when React must synchronize with a network connection, browser API, timer, subscription or third-party widget. It is not the default place for calculations or button-driven logic.", details: "Every effect should answer three questions: which external system is being synchronized, which reactive values control it, and how is it cleaned up? Correct dependencies make this contract explicit. Cleanup prevents duplicate listeners, stale subscriptions and work that outlives the component.", checklist: ["Move calculations out of effects", "Include every reactive dependency", "Return cleanup for listeners, subscriptions and timers"] },
      { title: "Custom hooks create behavioural APIs", introduction: "A useful custom hook gives a clear name to reusable stateful behaviour. It can hide browser integration, request state, validation or subscription mechanics while returning a small interface to the component.", details: "A custom hook does not share state automatically; it shares the logic that creates state. Keep its return value intentional and avoid exposing internal setters when a domain action such as open, close, retry or reset communicates more clearly.", checklist: ["Name hooks around a capability", "Return domain actions instead of implementation details", "Test behaviour through the hook’s public contract"] },
      { title: "Performance without premature optimization", introduction: "Hooks such as useMemo and useCallback are tools for avoiding specific expensive work or stabilizing references, not requirements for every value and function.", details: "First keep rendering pure and component boundaries focused. Profile the real interaction, then memoize calculations that are measurably expensive or references that cause meaningful child work. Simpler code is often faster to maintain and sufficiently fast to execute.", checklist: ["Measure before memoizing", "Keep render logic pure", "Use transitions for non-urgent expensive UI updates"] },
    ],
    practicalSteps: ["Audit one component and remove duplicated derived state", "Move user-triggered logic from an effect into its event handler", "Add cleanup to every external subscription", "Extract one genuinely repeated behaviour into a custom hook", "Profile before adding memoization"],
    conclusion: "Mastering Hooks is less about memorizing APIs and more about modelling ownership, synchronization and reuse. Components become easier to reason about when state is minimal, effects have a clear external purpose and custom hooks expose focused behavioural contracts.",
  },
  "2": {
    subtitle: "How Server Components change rendering, data access, JavaScript delivery and component architecture in the Next.js App Router.",
    takeaways: ["Server Components render on the server and do not add their component code to the client bundle", "Client Components remain essential for state, events and browser APIs", "Server and Client Components should be composed at deliberate boundaries", "Data access close to the server-rendered component reduces client waterfalls"],
    sections: [
      { title: "A different component execution model", introduction: "A Server Component executes in the server environment and produces a serialized React result. It can access databases, files and server-only secrets directly because its implementation is never shipped as browser JavaScript.", details: "This model is different from traditional server rendering of an entirely client-capable tree. The rendered output can stream into the page while interactive Client Components hydrate only where their JavaScript is actually required.", checklist: ["Keep pages and layouts server-first", "Access private infrastructure only on the server", "Send minimal serializable props across the client boundary"] },
      { title: "Choose the boundary by capability", introduction: "A component needs the client directive when it uses state, effects, event handlers or browser-only APIs. Pure presentation does not automatically require a Client Component, even when it is nested inside interactive UI.", details: "Place the client boundary as low as practical. A server-rendered product page can pass prepared product data into a small add-to-cart button. This keeps most of the route free of hydration cost while preserving the exact interaction users need.", checklist: ["Use client only for browser capabilities", "Pass server-rendered children into interactive shells", "Avoid turning an entire route into a Client Component"] },
      { title: "Data fetching without browser waterfalls", introduction: "Server Components can start data work during the route render, close to the source and before client JavaScript loads. Independent requests can run in parallel, while React cache can deduplicate repeated work within a request.", details: "The best architecture avoids sequential fetch chains created only by component nesting. Start independent promises early, await them near the component that needs the result, and use Suspense boundaries when parts of the page can stream independently.", checklist: ["Run independent requests with Promise.all", "Use cache for repeated server reads", "Stream slow sections behind meaningful Suspense fallbacks"] },
      { title: "Security and serialization", introduction: "Server execution makes secure data access possible, but data passed into a Client Component becomes visible to the browser. The boundary is therefore also a security and serialization boundary.", details: "Return only the fields the interface requires. Keep credentials and internal records in server-only modules, validate authorization before data access, and avoid passing large database documents when a small view model is sufficient.", checklist: ["Authorize every protected server operation", "Create minimal client-facing view models", "Keep secrets out of props and rendered output"] },
      { title: "Caching, revalidation and fresh content", introduction: "Server rendering does not mean every request must repeat every operation. Next.js provides route and data caching primitives that can balance freshness, performance and infrastructure cost.", details: "Choose caching based on the content contract: static marketing content can live longer, product inventory may need tags or timed revalidation, and user-specific information should remain request-bound. Make the freshness policy explicit instead of relying on accidental defaults.", checklist: ["Document the freshness requirement", "Use tags to invalidate related cached data", "Keep personalized responses out of shared caches"] },
    ],
    practicalSteps: ["Remove unnecessary use client directives from static components", "Move secure data reads into Server Components", "Parallelize independent route queries", "Add Suspense around independently slow sections", "Review every prop crossing into a Client Component"],
    conclusion: "Server Components are most valuable as an architectural constraint: server work stays near data and secrets, browser JavaScript is reserved for interaction, and the boundary between them becomes intentional. The result is often a faster page and a codebase with clearer responsibilities.",
  },
  "3": {
    subtitle: "A measurement-led playbook for faster loading, smoother interaction, stronger Core Web Vitals and sustainable performance work.",
    takeaways: ["Measure real pages before choosing an optimization", "Optimize the largest visual assets and critical rendering path first", "Ship JavaScript according to interaction priority", "Protect improvements with budgets and continuous monitoring"],
    sections: [
      { title: "Begin with evidence, not assumptions", introduction: "Performance work starts by measuring representative pages on realistic devices and networks. Lighthouse is useful for repeatable lab diagnostics, while field data reveals what actual visitors experience.", details: "Use the Core Web Vitals as user-centred signals: Largest Contentful Paint reflects loading, Interaction to Next Paint reflects responsiveness, and Cumulative Layout Shift reflects visual stability. Trace each poor metric back to a resource, task or layout decision.", checklist: ["Test mobile and desktop separately", "Compare lab results with field data", "Record a baseline before changing code"] },
      { title: "Treat images as layout and delivery decisions", introduction: "Images are frequently the largest bytes on a page and often become the LCP element. Correct dimensions, responsive sources and modern formats reduce transfer cost without compromising the design.", details: "Reserve intrinsic space to prevent layout shift, prioritize only the true above-the-fold image, and lazy-load content below the fold. Avoid sending a desktop-sized asset to a narrow mobile viewport and do not use compression as a substitute for correct dimensions.", checklist: ["Serve AVIF or WebP where appropriate", "Provide accurate sizes information", "Set width and height to protect layout stability"] },
      { title: "Control JavaScript execution cost", introduction: "Downloaded JavaScript must be parsed, compiled and executed before it can power an interaction. Large client bundles affect slower devices more severely than development machines suggest.", details: "Keep server-renderable work off the client, split optional experiences, and load heavy libraries only when a visitor requests the feature. Remove unused dependencies and inspect bundle changes during review instead of waiting for a performance regression.", checklist: ["Minimize client component boundaries", "Dynamically import optional heavy features", "Track route-level bundle growth"] },
      { title: "Make the critical rendering path intentional", introduction: "Fonts, stylesheets, scripts and server response time all influence when meaningful content appears. The initial document should contain useful content and the resources needed to render it should be discoverable early.", details: "Use optimized framework font loading, avoid render-blocking third-party scripts, cache stable assets and reduce server work on the critical request. Preload selectively: excessive priority competes for bandwidth and can delay the resource that matters most.", checklist: ["Optimize server response and caching", "Defer non-critical third-party code", "Prioritize only critical fonts and media"] },
      { title: "Build a performance culture", introduction: "One optimization pass cannot protect a growing product. New images, packages, experiments and tracking scripts gradually change the performance profile.", details: "Define budgets for images, JavaScript and key metrics; test important routes in continuous integration; and review real-user trends after deployment. A shared budget turns speed into a product requirement rather than optional polish.", checklist: ["Set route-specific budgets", "Automate Lighthouse or Web Vitals checks", "Investigate regressions before they become the baseline"] },
    ],
    practicalSteps: ["Capture mobile and desktop baselines", "Identify the LCP element and its request chain", "Resize and modernize oversized media", "Reduce or defer non-critical JavaScript", "Add a repeatable performance budget to delivery"],
    conclusion: "Fast websites come from a system of small, evidence-based decisions. Measure the user experience, fix the dominant bottleneck, verify the result, and keep monitoring. That cycle produces improvements that survive future features and real production traffic.",
  },
};

export function getArticleEditorial(id: string, title: string, description: string): ArticleEditorial {
  return editorials[id] ?? {
    subtitle: description,
    takeaways: ["Understand the core concept", "Apply the idea in a maintainable way", "Validate the result with real users and evidence"],
    sections: [{ title: `Understanding ${title}`, introduction: description, details: "Start with the user and business requirement, choose the simplest architecture that satisfies it, and verify the implementation through focused testing and production feedback." }],
    practicalSteps: ["Define the desired outcome", "Build a focused implementation", "Test the critical path", "Measure and refine"],
    conclusion: "Strong engineering combines clear requirements, deliberate implementation and continuous validation.",
  };
}
