export interface ProjectCaseStudy {
  category: string;
  objective: string;
  features: string[];
  architecture: string[];
  challenges: { problem: string; solution: string }[];
  workflow: string[];
  quality: string[];
  technologyReasons: { name: string; reason: string }[];
  security?: string[];
  stackGroups?: { label: string; items: string[] }[];
  documentation?: { url?: string; status: string; summary: string; captures: string[] };
}

type ProjectProfile = Pick<ProjectCaseStudy, "category" | "objective" | "features"> & {
  architecture?: string[];
  challenges?: ProjectCaseStudy["challenges"];
};

const profiles: Record<string, ProjectProfile> = {
  "20": { category: "Portfolio content platform API", objective: "Power a multilingual developer portfolio with secure administration, structured publishing workflows, media delivery, engagement and privacy-conscious first-party analytics.", features: ["JWT access and rotating refresh-token authentication", "Role-based users, profiles and administration", "Projects, articles, comments, likes and taxonomy APIs", "Cloudinary image and PDF upload workflows", "Contact inbox, newsletter and dashboard reporting", "Consent-based analytics with session/path deduplication"], architecture: ["Strict TypeScript service/controller/router separation", "MongoDB models and indexed Mongoose queries", "Serverless-ready database connection middleware", "Standard response envelopes, typed errors and pagination"], challenges: [{ problem: "Authentication must work between separately deployed frontend and API origins.", solution: "Credentialed CORS, secure HttpOnly refresh cookies, short-lived bearer access tokens and refresh rotation keep the cross-origin flow controlled." }, { problem: "React rerenders and network retries can inflate traffic metrics.", solution: "Hashed visitor/session identities and a unique session-path database index make page-view recording idempotent." }, { problem: "Public forms and content APIs face abuse and unsafe input.", solution: "Route-specific rate limits, Joi validation, recursive Mongo key sanitization and explicit origin allowlists reduce the attack surface." }] },
  "21": { category: "Healthcare scheduling API", objective: "Coordinate patients, doctors, secretaries, hospitals and administrators through reliable identity, discovery and appointment-booking workflows.", features: ["Multi-role authentication and token-version revocation", "Doctor profiles, locations, availability and unavailable dates", "Patient and staff-assisted appointment booking", "Hospital-doctor association and speciality catalogues", "Conversation threads and message attachments", "Swagger contract plus smoke and stateful integration suites"], architecture: ["Domain-focused Express routes, controllers and Mongoose models", "Role-aware authorization around patient, doctor, secretary and admin data", "Atomic appointment slot reservation documents with expiry", "Server-authoritative fees and standardized response envelopes"], challenges: [{ problem: "Two users can attempt to reserve the same doctor slot concurrently.", solution: "A deterministic compound reservation key and MongoDB uniqueness convert racing requests into a controlled 409 conflict." }, { problem: "Healthcare actors require different scopes over the same appointment data.", solution: "Role and ownership checks resolve doctor, secretary, patient and administrator access before every sensitive workflow." }, { problem: "Client-supplied appointment fees could be manipulated.", solution: "The API derives new and returning-patient fees from authoritative location records before persisting the booking." }] },
  "22": { category: "E-commerce authentication API", objective: "Provide a compact TypeScript backend for account registration, secure cookie login, current-user sessions and customer record administration.", features: ["Username and email uniqueness checks", "bcrypt password hashing", "JWT authentication through HttpOnly cookies", "Cross-origin credential support", "User create, read, update and delete endpoints", "Protected current-user identity endpoint"], architecture: ["Express 5 API with focused user routes and controller functions", "MongoDB persistence through a Mongoose user model", "Cookie-parsing authentication middleware", "Environment-driven database, frontend origin and JWT configuration"], challenges: [{ problem: "The deployed storefront and API use different origins.", solution: "Credentialed CORS and production SameSite=None secure cookies allow the authenticated browser session to cross origins." }, { problem: "Duplicate usernames or email addresses create ambiguous identities.", solution: "Registration checks both fields and returns explicit 409 conflict responses before hashing and persistence." }, { problem: "Protected requests need a simple identity handoff.", solution: "Middleware verifies the signed cookie, attaches the decoded identity and blocks missing or expired sessions." }] },
  "23": { category: "Commerce operations API", objective: "Support a broad e-commerce back office with secure sessions, catalogue and order management, inventory integrity, reporting, support and contract-driven documentation.", features: ["182 documented API operations across commerce domains", "Orders, products, catalogues, customers, vendors and purchasing", "Income, expense, invoice and dashboard reporting", "Atomic stock adjustments with negative-inventory protection", "Support conversations, settings and role-aware administration", "Generated OpenAPI contract and comprehensive Laravel feature tests"], architecture: ["Laravel 12 and PHP 8.2 with Eloquent-backed resource definitions", "Config-driven CRUD engine shared across dozens of resources", "Cookie-based JWT access and refresh sessions", "Database transactions, row locks and shared cache rate limiting"], challenges: [{ problem: "A large resource surface can drift between validation, CRUD logic and API documentation.", solution: "Shared resource definitions generate field rules and OpenAPI schemas from one source of truth." }, { problem: "Repeated or edited stock adjustments can double-apply inventory changes.", solution: "Transactional row locks calculate only the approved delta and rollback invalid or negative-stock operations." }, { problem: "Serverless instances cannot rely on process-local rate-limit state.", solution: "A shared database cache enforces login throttling consistently across Vercel function instances." }] },
  "19": { category: "Real-estate platform", objective: "Turn a multi-page property experience into a fast, content-rich static website that remains easy to browse on every device.", features: ["Property catalogue and individual property pages", "Agent directory with dynamic agent profiles", "Service catalogue and location-specific service routes", "Company, reviews, FAQ, contact and legal pages", "Content collections for blog, tags, categories and authors", "Motion-enhanced responsive navigation and calls to action"], architecture: ["Astro static routes for low-JavaScript delivery", "Dynamic getStaticPaths routes for properties, agents and services", "Structured data modules for properties, agents and service content", "Reusable layouts and data-driven content collections"], challenges: [{ problem: "A large number of property and service page types needed a consistent design.", solution: "Reusable Astro layouts and typed data modules keep the visual language and content structure aligned." }, { problem: "Rich imagery and motion could make property browsing feel heavy.", solution: "Static generation, optimized image formats and progressively enhanced animation protect the initial experience." }] },
  "18": { category: "Online learning platform", objective: "Translate a detailed Figma concept into a responsive learning marketplace with discoverable courses and creator-led content.", features: ["Course discovery and featured-course sections", "Search, filtering, sorting and pagination flows", "Course overview, lesson and review pages", "Creator profile and creator course collection", "Sign-in and registration experiences", "Metadata, sitemap, manifest and structured course data"], architecture: ["Next.js App Router with server-rendered route composition", "Dynamic course routes backed by reusable course data", "Small reusable UI primitives and focused section components", "URL-driven search state for shareable discovery results"], challenges: [{ problem: "The Figma layout used expressive artwork and strict visual spacing across breakpoints.", solution: "Responsive design tokens, reusable primitives and dedicated artwork components preserve the composition without sacrificing mobile usability." }, { problem: "Course information appears across discovery, detail, lesson and review views.", solution: "A shared typed course model prevents duplicated content and keeps every route synchronized." }] },
  "17": { category: "Nationwide rental platform", objective: "Rebuild a high-volume food-truck rental website into a responsive, conversion-focused and search-ready experience.", features: ["Food-truck rental service catalogue", "Nationwide state, region and city landing pages", "Rental calculator and lead-generation journeys", "Recovered content routes with canonical URL handling", "Public sitemap, robots rules and structured data", "Responsive emergency and contact calls to action"], architecture: ["React and TypeScript interface built with Vite", "Build-time prerendering for a large route inventory", "Route registry separating indexable and private content", "Firebase-backed protected lead submission workflow"], challenges: [{ problem: "Hundreds of recovered content routes needed stable canonical URLs and valid internal links.", solution: "A deterministic prerender pipeline, route registry and automated indexing checks validate every generated page." }, { problem: "SEO content had to remain useful while still guiding visitors toward a rental enquiry.", solution: "Service-specific content, contextual calls to action and structured metadata balance discovery with conversion." }] },
  "16": { category: "Commercial rental platform", objective: "Create a trustworthy nationwide platform for urgent temporary dishwashing facility rentals and complex service-area discovery.", features: ["Equipment inventory and model detail pages", "Interactive rental planning calculator", "State, region and city service-area directories", "Industry-specific solution pages", "Emergency callback and quote request flows", "Canonical URLs, sitemap, robots and JSON-LD generation"], architecture: ["React and TypeScript application powered by Vite", "Static prerender pipeline for indexable public routes", "Typed content and route configuration as a single source of truth", "Firebase App Check protected form submission"], challenges: [{ problem: "Users need actionable planning information without presenting an unapproved final quote.", solution: "The calculator creates a structured project brief and clearly separates estimates from confirmed commercial pricing." }, { problem: "Nationwide location coverage can create duplicate or low-value pages.", solution: "Controlled route registries, unique editorial content and canonical validation keep the architecture deliberate." }] },
  "5": { category: "Healthcare web application", objective: "Present hospital services and patient workflows through a clean, scalable and responsive healthcare interface.", features: ["Healthcare service discovery", "Appointment-oriented user journeys", "Patient-focused responsive interface", "Reusable dashboard-ready UI patterns", "Typed data fetching and loading states", "Accessible navigation and content hierarchy"] },
  "11": { category: "Business dashboard", objective: "Build a clear CRM-style dashboard for monitoring operational data and completing common administrative tasks.", features: ["Responsive dashboard shell", "Data tables and operational summaries", "Reusable cards and status treatments", "Desktop and mobile navigation", "AJAX-ready interaction patterns", "Lightweight framework-independent delivery"] },
  "2": { category: "Trading dashboard", objective: "Turn financial information into a readable, responsive interface with clear charts and navigation.", features: ["Market-focused dashboard layout", "Interactive Recharts visualizations", "Reusable Next.js sections", "Responsive information cards", "Clear data hierarchy", "Fast client-side navigation"] },
  "3": { category: "Garments operations interface", objective: "Digitize garment workflow visibility through a responsive operational frontend.", features: ["Production workflow presentation", "Inventory and order views", "Responsive operational layout", "Interactive visual effects", "Reusable React sections", "Clear management navigation"] },
  "4": { category: "Learning landing experience", objective: "Create an approachable course-learning experience that guides visitors toward available educational content.", features: ["Course-focused landing page", "Responsive content sections", "Clear enrolment calls to action", "Reusable React components", "Mobile-first navigation", "Accessible visual hierarchy"] },
  "6": { category: "Full-stack portfolio", objective: "Build a maintainable personal platform where projects, skills and professional content can be presented dynamically.", features: ["Project and skill showcases", "Responsive portfolio sections", "Typed Next.js components", "Contact and professional profile flows", "Reusable design system", "SEO-ready page structure"] },
  "7": { category: "JavaScript utility", objective: "Make secure password creation quick and understandable with immediate visual feedback.", features: ["Configurable password length", "Character-set controls", "Instant password generation", "Clipboard-ready output", "Responsive utility layout", "Input validation and feedback"] },
  "8": { category: "E-commerce platform", objective: "Deliver a complete product discovery and purchasing interface backed by persistent application data.", features: ["Product catalogue", "Cart and checkout journeys", "Customer authentication", "Order-oriented workflows", "Responsive commerce UI", "MongoDB data persistence"] },
  "9": { category: "Airline booking interface", objective: "Simplify flight exploration and booking through a focused, responsive React experience.", features: ["Flight discovery interface", "Booking flow", "Responsive search experience", "Reusable React components", "Clear itinerary presentation", "Mobile-friendly navigation"] },
  "12": { category: "Premium marketing theme", objective: "Deliver a polished, responsive commercial theme with an automated frontend workflow.", features: ["Responsive marketing sections", "Reusable HTML partials", "Tailwind-based styling", "Gulp development pipeline", "Optimized production assets", "Cross-device navigation"] },
  "13": { category: "Premium Next.js theme", objective: "Rebuild a premium visual concept with modular Next.js components, responsive layouts and SEO-friendly rendering.", features: ["Reusable page sections", "Responsive premium layout", "Typed component composition", "Server-rendered pages", "Optimized navigation", "Maintainable Tailwind styling"] },
  "14": { category: "Technology landing page", objective: "Create a modern company landing page that communicates services clearly and performs smoothly across devices.", features: ["Service-led content sections", "Responsive navigation", "Modern visual hierarchy", "Reusable Next.js components", "Conversion-focused calls to action", "SEO-friendly page structure"] },
  "15": { category: "Emergency local-service website", objective: "Help visitors find urgent locksmith services quickly through a direct, mobile-friendly local landing experience.", features: ["Emergency service presentation", "Prominent call actions", "Responsive local-service layout", "Fast static delivery", "Clear trust signals", "Contact-focused navigation"] },
};

const backendDetails: Record<string, Pick<ProjectCaseStudy, "security" | "stackGroups" | "documentation">> = {
  "20": {
    security: ["Helmet security headers and explicit CORS allowlist", "bcrypt password hashing and password-change token invalidation", "Short-lived JWT access tokens with rotating HttpOnly refresh cookies", "Joi validation, Mongo key sanitization and scoped rate limiting"],
    stackGroups: [{ label: "Runtime", items: ["Node.js", "Express", "TypeScript"] }, { label: "Data", items: ["MongoDB", "Mongoose"] }, { label: "Platform", items: ["Cloudinary", "Nodemailer", "Vercel"] }, { label: "Quality", items: ["Swagger/OpenAPI", "ESLint", "Strict TypeScript"] }],
    documentation: { url: "https://rashaduldev-backend.vercel.app/api-docs", status: "Live Swagger UI", summary: "The production API exposes interactive authentication, portfolio content, engagement, upload, dashboard and analytics contracts.", captures: ["Swagger API overview and module navigation", "Authentication login and refresh-token contract", "Admin analytics response schema"] },
  },
  "21": {
    security: ["JWT verification with token-version revocation", "Patient, doctor, secretary and administrator authorization boundaries", "Helmet CSP, credentialed CORS and IP-aware rate limiting", "Server-side fee calculation and booking ownership validation"],
    stackGroups: [{ label: "Runtime", items: ["Node.js 20", "Express 4", "TypeScript"] }, { label: "Data", items: ["MongoDB", "Mongoose"] }, { label: "Security", items: ["JWT", "bcryptjs", "Helmet"] }, { label: "Quality", items: ["Swagger/OpenAPI", "Smoke Tests", "Integration Tests"] }],
    documentation: { url: "https://hospitalia-web-backend.vercel.app/api-docs", status: "Live Swagger UI", summary: "The healthcare contract documents authentication, provider discovery, hospitals, availability, appointment booking, administration and chat workflows.", captures: ["Swagger healthcare domain overview", "Appointment availability and booking operation", "Role-protected response and error schemas"] },
  },
  "22": {
    security: ["bcrypt password hashing", "HttpOnly JWT cookie with Secure and SameSite=None in production", "Credentialed CORS restricted to configured storefront origins", "Protected current-user middleware"],
    stackGroups: [{ label: "Runtime", items: ["Node.js", "Express 5", "TypeScript"] }, { label: "Data", items: ["MongoDB", "Mongoose"] }, { label: "Security", items: ["JWT", "bcrypt", "Cookie Parser"] }],
    documentation: { url: "https://a-to-z-backend.vercel.app/", status: "Live API health endpoint", summary: "The service is deployed and responsive. Swagger/OpenAPI is not implemented in the repository yet, so the capture plan identifies the documentation work required without claiming a live contract.", captures: ["Create Swagger user/auth endpoint overview", "Capture HttpOnly login response and Set-Cookie flow", "Capture current-user success and 401 schemas"] },
  },
  "23": {
    security: ["HttpOnly access and refresh JWT cookies with auth-version revocation", "Admin and superadmin role middleware", "Origin verification and credentialed CORS", "Validation, throttling and protected resource ownership"],
    stackGroups: [{ label: "Runtime", items: ["PHP 8.2", "Laravel 12"] }, { label: "Data", items: ["MySQL", "Eloquent ORM", "Database Cache"] }, { label: "Security", items: ["Firebase JWT", "Role Middleware", "Rate Limiting"] }, { label: "Quality", items: ["Generated OpenAPI", "PHPUnit", "182-operation coverage"] }],
    documentation: { status: "Swagger implemented; public deployment pending", summary: "Source includes `/api/docs` and `/api/openapi.json`, generated from shared resource definitions. The currently discoverable deployment does not expose the docs page, so no dead live link is published.", captures: ["Swagger dashboard with resource groups", "Cookie-authenticated login Try It Out flow", "Order, inventory and report schema examples"] },
  },
};

const reasonFor = (technology: string) => {
  const value = technology.toLowerCase();
  if (value.includes("next")) return "Server rendering, route composition and production-grade React delivery.";
  if (value.includes("astro")) return "Content-first static output with minimal client-side JavaScript.";
  if (value.includes("typescript")) return "Safer refactoring and explicit contracts between data and UI.";
  if (value.includes("tailwind")) return "Consistent responsive styling through reusable design tokens.";
  if (value.includes("react")) return "Composable interactive UI with reusable stateful components.";
  if (value.includes("mongo")) return "Flexible persistent storage for application and user-generated data.";
  if (value.includes("firebase")) return "Managed authentication and secure cloud-connected workflows.";
  if (value.includes("express") || value.includes("node")) return "A focused JavaScript API layer for business logic and data access.";
  if (value.includes("laravel")) return "A structured PHP application layer with routing, validation, ORM and test tooling.";
  if (value.includes("php")) return "A mature server runtime suited to Laravel's production request lifecycle.";
  if (value.includes("mysql")) return "Relational integrity and transactional storage for commerce operations.";
  if (value.includes("swagger") || value.includes("openapi")) return "An executable API contract for discovery, integration and verification.";
  return `Supports the ${technology.trim()} layer of the implementation.`;
};

export function getProjectCaseStudy(id: string, title: string, description: string, technologies: string[]): ProjectCaseStudy {
  const profile = profiles[id] ?? { category: "Web application", objective: description, features: ["Responsive interface", "Reusable components", "Clear navigation", "Production-ready deployment"] };
  return {
    ...profile,
    ...backendDetails[id],
    architecture: profile.architecture ?? ["Feature-focused component structure", "Reusable presentation and interaction patterns", "Responsive layout rules shared across views", "Separated content, styling and application behaviour"],
    challenges: profile.challenges ?? [{ problem: `Turning ${title} requirements into a consistent experience across screen sizes.`, solution: "A mobile-first component system and progressive responsive enhancements keep content usable at every breakpoint." }, { problem: "Keeping the codebase easy to extend while delivering the required interface quickly.", solution: "Reusable sections, centralized data and focused responsibilities reduce duplication and future maintenance cost." }],
    workflow: ["Requirements and content audit", "Information architecture and responsive planning", "Component and data modelling", "Feature implementation and integration", "Cross-device testing and production refinement"],
    quality: ["Responsive layouts", "Semantic content structure", "Reusable implementation", "Clear interaction feedback", "Performance-conscious assets", "Maintainable code organization"],
    technologyReasons: technologies.filter(Boolean).map((name) => ({ name: name.trim(), reason: reasonFor(name) })),
  };
}
