export interface ProjectCaseStudy {
  category: string;
  objective: string;
  features: string[];
  architecture: string[];
  challenges: { problem: string; solution: string }[];
  workflow: string[];
  quality: string[];
  technologyReasons: { name: string; reason: string }[];
}

type ProjectProfile = Pick<ProjectCaseStudy, "category" | "objective" | "features"> & {
  architecture?: string[];
  challenges?: ProjectCaseStudy["challenges"];
};

const profiles: Record<string, ProjectProfile> = {
  "19": { category: "Real-estate platform", objective: "Turn a multi-page property experience into a fast, content-rich static website that remains easy to browse on every device.", features: ["Property catalogue and individual property pages", "Agent directory with dynamic agent profiles", "Service catalogue and location-specific service routes", "Company, reviews, FAQ, contact and legal pages", "Content collections for blog, tags, categories and authors", "Motion-enhanced responsive navigation and calls to action"], architecture: ["Astro static routes for low-JavaScript delivery", "Dynamic getStaticPaths routes for properties, agents and services", "Structured data modules for properties, agents and service content", "Reusable layouts and data-driven content collections"], challenges: [{ problem: "A large number of property and service page types needed a consistent design.", solution: "Reusable Astro layouts and typed data modules keep the visual language and content structure aligned." }, { problem: "Rich imagery and motion could make property browsing feel heavy.", solution: "Static generation, optimized image formats and progressively enhanced animation protect the initial experience." }] },
  "18": { category: "Online learning platform", objective: "Translate a detailed Figma concept into a responsive learning marketplace with discoverable courses and creator-led content.", features: ["Course discovery and featured-course sections", "Search, filtering, sorting and pagination flows", "Course overview, lesson and review pages", "Creator profile and creator course collection", "Sign-in and registration experiences", "Metadata, sitemap, manifest and structured course data"], architecture: ["Next.js App Router with server-rendered route composition", "Dynamic course routes backed by reusable course data", "Small reusable UI primitives and focused section components", "URL-driven search state for shareable discovery results"], challenges: [{ problem: "The Figma layout used expressive artwork and strict visual spacing across breakpoints.", solution: "Responsive design tokens, reusable primitives and dedicated artwork components preserve the composition without sacrificing mobile usability." }, { problem: "Course information appears across discovery, detail, lesson and review views.", solution: "A shared typed course model prevents duplicated content and keeps every route synchronized." }] },
  "17": { category: "Nationwide rental platform", objective: "Rebuild a high-volume food-truck rental website into a responsive, conversion-focused and search-ready experience.", features: ["Food-truck rental service catalogue", "Nationwide state, region and city landing pages", "Rental calculator and lead-generation journeys", "Recovered content routes with canonical URL handling", "Public sitemap, robots rules and structured data", "Responsive emergency and contact calls to action"], architecture: ["React and TypeScript interface built with Vite", "Build-time prerendering for a large route inventory", "Route registry separating indexable and private content", "Firebase-backed protected lead submission workflow"], challenges: [{ problem: "Hundreds of recovered content routes needed stable canonical URLs and valid internal links.", solution: "A deterministic prerender pipeline, route registry and automated indexing checks validate every generated page." }, { problem: "SEO content had to remain useful while still guiding visitors toward a rental enquiry.", solution: "Service-specific content, contextual calls to action and structured metadata balance discovery with conversion." }] },
  "16": { category: "Commercial rental platform", objective: "Create a trustworthy nationwide platform for urgent temporary dishwashing facility rentals and complex service-area discovery.", features: ["Equipment inventory and model detail pages", "Interactive rental planning calculator", "State, region and city service-area directories", "Industry-specific solution pages", "Emergency callback and quote request flows", "Canonical URLs, sitemap, robots and JSON-LD generation"], architecture: ["React and TypeScript application powered by Vite", "Static prerender pipeline for indexable public routes", "Typed content and route configuration as a single source of truth", "Firebase App Check protected form submission"], challenges: [{ problem: "Users need actionable planning information without presenting an unapproved final quote.", solution: "The calculator creates a structured project brief and clearly separates estimates from confirmed commercial pricing." }, { problem: "Nationwide location coverage can create duplicate or low-value pages.", solution: "Controlled route registries, unique editorial content and canonical validation keep the architecture deliberate." }] },
  "5": { category: "Healthcare web application", objective: "Present hospital services and patient workflows through a clean, scalable and responsive healthcare interface.", features: ["Healthcare service discovery", "Appointment-oriented user journeys", "Patient-focused responsive interface", "Reusable dashboard-ready UI patterns", "Typed data fetching and loading states", "Accessible navigation and content hierarchy"] },
  "11": { category: "Business dashboard", objective: "Build a clear CRM-style dashboard for monitoring operational data and completing common administrative tasks.", features: ["Responsive dashboard shell", "Data tables and operational summaries", "Reusable cards and status treatments", "Desktop and mobile navigation", "AJAX-ready interaction patterns", "Lightweight framework-independent delivery"] },
  "1": { category: "Travel booking platform", objective: "Provide a complete travel discovery and booking experience with secure account and content workflows.", features: ["Tour and destination discovery", "Booking-oriented user flows", "Firebase authentication", "Responsive traveller dashboard", "MongoDB-backed application data", "Client and server separation"] },
  "2": { category: "Trading dashboard", objective: "Turn financial information into a readable, responsive interface with clear charts and navigation.", features: ["Market-focused dashboard layout", "Interactive Recharts visualizations", "Reusable Next.js sections", "Responsive information cards", "Clear data hierarchy", "Fast client-side navigation"] },
  "3": { category: "Garments operations interface", objective: "Digitize garment workflow visibility through a responsive operational frontend.", features: ["Production workflow presentation", "Inventory and order views", "Responsive operational layout", "Interactive visual effects", "Reusable React sections", "Clear management navigation"] },
  "4": { category: "Learning landing experience", objective: "Create an approachable course-learning experience that guides visitors toward available educational content.", features: ["Course-focused landing page", "Responsive content sections", "Clear enrolment calls to action", "Reusable React components", "Mobile-first navigation", "Accessible visual hierarchy"] },
  "6": { category: "Full-stack portfolio", objective: "Build a maintainable personal platform where projects, skills and professional content can be presented dynamically.", features: ["Project and skill showcases", "Responsive portfolio sections", "Typed Next.js components", "Contact and professional profile flows", "Reusable design system", "SEO-ready page structure"] },
  "7": { category: "JavaScript utility", objective: "Make secure password creation quick and understandable with immediate visual feedback.", features: ["Configurable password length", "Character-set controls", "Instant password generation", "Clipboard-ready output", "Responsive utility layout", "Input validation and feedback"] },
  "8": { category: "E-commerce platform", objective: "Deliver a complete product discovery and purchasing interface backed by persistent application data.", features: ["Product catalogue", "Cart and checkout journeys", "Customer authentication", "Order-oriented workflows", "Responsive commerce UI", "MongoDB data persistence"] },
  "9": { category: "Airline booking interface", objective: "Simplify flight exploration and booking through a focused, responsive React experience.", features: ["Flight discovery interface", "Booking flow", "Responsive search experience", "Reusable React components", "Clear itinerary presentation", "Mobile-friendly navigation"] },
  "10": { category: "REST API service", objective: "Provide a secure backend foundation for travel content, users and protected application workflows.", features: ["Express REST endpoints", "MongoDB and Mongoose persistence", "JWT authentication", "Protected resource access", "Structured API responses", "Deployment-ready Node.js service"] },
  "12": { category: "Premium marketing theme", objective: "Deliver a polished, responsive commercial theme with an automated frontend workflow.", features: ["Responsive marketing sections", "Reusable HTML partials", "Tailwind-based styling", "Gulp development pipeline", "Optimized production assets", "Cross-device navigation"] },
  "13": { category: "Premium Next.js theme", objective: "Rebuild a premium visual concept with modular Next.js components, responsive layouts and SEO-friendly rendering.", features: ["Reusable page sections", "Responsive premium layout", "Typed component composition", "Server-rendered pages", "Optimized navigation", "Maintainable Tailwind styling"] },
  "14": { category: "Technology landing page", objective: "Create a modern company landing page that communicates services clearly and performs smoothly across devices.", features: ["Service-led content sections", "Responsive navigation", "Modern visual hierarchy", "Reusable Next.js components", "Conversion-focused calls to action", "SEO-friendly page structure"] },
  "15": { category: "Emergency local-service website", objective: "Help visitors find urgent locksmith services quickly through a direct, mobile-friendly local landing experience.", features: ["Emergency service presentation", "Prominent call actions", "Responsive local-service layout", "Fast static delivery", "Clear trust signals", "Contact-focused navigation"] },
};

const reasonFor = (technology: string) => {
  const value = technology.toLowerCase();
  if (value.includes("next")) return "Server rendering, route composition and production-grade React delivery.";
  if (value.includes("astro")) return "Content-first static output with minimal client-side JavaScript.";
  if (value.includes("typescript")) return "Safer refactoring and explicit contracts between data and UI.";
  if (value.includes("tailwind")) return "Consistent responsive styling through reusable design tokens.";
  if (value.includes("react")) return "Composable interactive UI with reusable stateful components.";
  if (value.includes("mongo")) return "Flexible persistent storage for application and user-generated data.";
  if (value.includes("firebase")) return "Managed authentication and secure cloud-connected workflows.";
  if (value.includes("express") || value.includes("node")) return "A focused JavaScript API layer for business logic and data access.";
  return `Supports the ${technology.trim()} layer of the implementation.`;
};

export function getProjectCaseStudy(id: string, title: string, description: string, technologies: string[]): ProjectCaseStudy {
  const profile = profiles[id] ?? { category: "Web application", objective: description, features: ["Responsive interface", "Reusable components", "Clear navigation", "Production-ready deployment"] };
  return {
    ...profile,
    architecture: profile.architecture ?? ["Feature-focused component structure", "Reusable presentation and interaction patterns", "Responsive layout rules shared across views", "Separated content, styling and application behaviour"],
    challenges: profile.challenges ?? [{ problem: `Turning ${title} requirements into a consistent experience across screen sizes.`, solution: "A mobile-first component system and progressive responsive enhancements keep content usable at every breakpoint." }, { problem: "Keeping the codebase easy to extend while delivering the required interface quickly.", solution: "Reusable sections, centralized data and focused responsibilities reduce duplication and future maintenance cost." }],
    workflow: ["Requirements and content audit", "Information architecture and responsive planning", "Component and data modelling", "Feature implementation and integration", "Cross-device testing and production refinement"],
    quality: ["Responsive layouts", "Semantic content structure", "Reusable implementation", "Clear interaction feedback", "Performance-conscious assets", "Maintainable code organization"],
    technologyReasons: technologies.filter(Boolean).map((name) => ({ name: name.trim(), reason: reasonFor(name) })),
  };
}
