import Link from "next/link";
import { ArrowUpRight, Camera, FileJson, LockKeyhole, ServerCog } from "lucide-react";
import type { ProjectCaseStudy } from "@/lib/projectCaseStudies";

export default function ProjectApiDocumentation({ study }: { study: ProjectCaseStudy }) {
  if (!study.documentation) return null;
  return <section className="space-y-8">
    <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]">
      <div className="rounded-[2rem] border border-primary/25 bg-primary/5 p-6 sm:p-8"><div className="flex items-center gap-3 text-primary"><FileJson className="h-6 w-6" /><p className="text-xs font-bold uppercase tracking-[.2em]">Interactive API documentation</p></div><h2 className="mt-4 text-3xl font-black">Explore the API contract</h2><p className="mt-4 leading-8 text-muted-foreground">{study.documentation.summary}</p><div className="mt-6 flex flex-wrap items-center gap-3"><span className="rounded-full border border-primary/25 bg-background px-3 py-1.5 text-xs font-bold text-primary">{study.documentation.status}</span>{study.documentation.url && <Link href={study.documentation.url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground">Open API endpoint <ArrowUpRight className="h-4 w-4" /></Link>}</div></div>
      <div className="rounded-[2rem] bg-zinc-950 p-6 text-white sm:p-8"><LockKeyhole className="h-7 w-7 text-primary" /><h2 className="mt-5 text-2xl font-black">Security engineering</h2><ul className="mt-5 space-y-3">{study.security?.map((item) => <li key={item} className="flex gap-3 text-sm leading-6 text-zinc-300"><ServerCog className="mt-1 h-4 w-4 shrink-0 text-primary" />{item}</li>)}</ul></div>
    </div>
    {study.stackGroups && <div><p className="text-xs font-bold uppercase tracking-[.2em] text-primary">Stack by responsibility</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{study.stackGroups.map((group) => <div key={group.label} className="rounded-2xl border border-border bg-card p-5"><h3 className="font-black">{group.label}</h3><div className="mt-3 flex flex-wrap gap-2">{group.items.map((item) => <span key={item} className="rounded-lg bg-muted px-2.5 py-1.5 text-xs font-semibold">{item}</span>)}</div></div>)}</div></div>}
    <div><div className="mb-5 flex items-center gap-3"><Camera className="h-5 w-5 text-primary" /><div><p className="text-xs font-bold uppercase tracking-[.2em] text-primary">Swagger capture plan</p><h2 className="mt-1 text-2xl font-black">Recommended documentation visuals</h2></div></div><div className="grid gap-4 md:grid-cols-3">{study.documentation.captures.map((capture, index) => <div key={capture} className="rounded-2xl border border-dashed border-primary/35 bg-gradient-to-br from-primary/10 to-transparent p-6"><span className="font-mono text-xs font-black text-primary">CAPTURE {String(index + 1).padStart(2, "0")}</span><p className="mt-8 font-bold leading-7">{capture}</p><p className="mt-3 text-xs leading-5 text-muted-foreground">Replace this capture target with the final production Swagger screenshot.</p></div>)}</div></div>
  </section>;
}
